spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - PUT
                  - POST
                  - DELETE
                  - OPTIONS
          routes:
            - id: admin-server
              uri: lb://ADMIN-SERVER
              predicates:
                - Path=/api/admin-server/**
              filters:
                - StripPrefix=2



